'use strict';
const getPath=(object,path)=>{const normalized=path.replace(/^destinations\.(\d+)\./,'destinations.items.$1.');return normalized.split('.').reduce((value,key)=>value?.[Number.isInteger(Number(key))?Number(key):key],object)};
async function loadContent(){if(location.protocol==='file:')return;try{const response=await fetch('/api/content',{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const content=await response.json();document.querySelectorAll('[data-content]').forEach(element=>{const value=getPath(content,element.dataset.content);if(typeof value==='string')element.textContent=value});document.querySelectorAll('[data-image]').forEach(image=>{const value=getPath(content,image.dataset.image);if(typeof value==='string'&&value)image.src=value});document.querySelectorAll('[data-link]').forEach(element=>{const value=getPath(content,element.dataset.link);if(typeof value!=='string'||!value)return;const allowed=/^(?:https?:|mailto:|tel:|#|\/)/i.test(value);if(!allowed)return;if(element.tagName==='IFRAME'){if(/^https?:/i.test(value))element.src=value}else element.href=value});const favicon=document.querySelector('[data-favicon]');if(favicon&&content.brand.faviconImage){const joiner=content.brand.faviconImage.includes('?')?'&':'?';favicon.href=`${content.brand.faviconImage}${joiner}v=${encodeURIComponent(content.updatedAt||'default')}`}document.querySelectorAll('[data-contact]').forEach(contact=>contact.href=`mailto:${content.brand.contact}`);document.title=`${content.brand.name} — Sipalay City`}catch{const status=document.querySelector('.page-status');status.textContent='Live content is temporarily unavailable. Showing the latest built-in version.';status.hidden=false}}
const howModal=document.querySelector('#how-modal');
const howModalClose=howModal?.querySelector('.how-modal-close');
let howModalTrigger=null;
function closeHowModal(){if(!howModal)return;if(typeof howModal.close==='function'&&howModal.open)howModal.close();else howModal.removeAttribute('open')}
function openHowModal(trigger){if(!howModal)return;howModalTrigger=trigger||document.activeElement;if(typeof howModal.showModal==='function'){if(!howModal.open)howModal.showModal()}else howModal.setAttribute('open','');document.body.classList.add('modal-open')}
document.querySelectorAll('[data-how-modal-open]').forEach(trigger=>trigger.addEventListener('click',event=>{event.preventDefault();openHowModal(trigger)}));
howModalClose?.addEventListener('click',closeHowModal);
howModal?.addEventListener('click',event=>{if(event.target===howModal)closeHowModal()});
howModal?.addEventListener('close',()=>{document.body.classList.remove('modal-open');howModalTrigger?.focus();howModalTrigger=null});
howModal?.addEventListener('cancel',()=>document.body.classList.remove('modal-open'));
if(location.hash==='#how-modal')openHowModal();
const passModal=document.querySelector('#pass-modal');
const passModalClose=passModal?.querySelector('.pass-modal-close');
const passForm=document.querySelector('#passForm');
const visitDateInput=passForm?.elements.visitDate;
const discountIdInput=passForm?.elements.discountId;
const registrationCounts={adult:1,foreign:0,senior:0,child:0};
const registrationRates={adult:50,foreign:100,senior:25,child:0};
let currentPass=null;
let passModalTrigger=null;
function closePassModal(){if(!passModal)return;if(typeof passModal.close==='function'&&passModal.open)passModal.close();else passModal.removeAttribute('open')}
function showRegistrationStep(step){passModal?.querySelectorAll('[data-pass-step]').forEach(section=>section.hidden=Number(section.dataset.passStep)!==step);const progress=[...passModal.querySelectorAll('[data-pass-progress]')];progress.forEach(item=>{const value=Number(item.dataset.passProgress);item.classList.toggle('active',value===step);item.classList.toggle('complete',value<step)});passModal.querySelectorAll('.pass-progress i').forEach((line,index)=>line.classList.toggle('complete',index<step-1));passModal.querySelector('.pass-modal-card').scrollTop=0}
function openPassModal(trigger){if(!passModal)return;passModalTrigger=trigger||document.activeElement;showRegistrationStep(1);passModal.querySelectorAll('.pass-form-status').forEach(status=>{status.textContent='';status.classList.remove('success')});const today=new Date();visitDateInput.min=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);if(typeof passModal.showModal==='function'){if(!passModal.open)passModal.showModal()}else passModal.setAttribute('open','');document.body.classList.add('modal-open')}
document.querySelectorAll('[data-pass-modal-open]').forEach(trigger=>trigger.addEventListener('click',event=>{event.preventDefault();openPassModal(trigger)}));
function registrationTotal(){return Object.keys(registrationCounts).reduce((total,key)=>total+registrationCounts[key]*registrationRates[key],0)}
function groupLabel(key){return {adult:'Adults (Local)',foreign:'Foreign Visitors',senior:'Senior/PWD/Student',child:'Children below 8'}[key]}
function updateGroupRow(key){const row=passModal.querySelector(`[data-group="${key}"]`);row.querySelector('output').textContent=registrationCounts[key];row.querySelector('[data-count-action="minus"]').disabled=key==='adult'?registrationCounts[key]<=1:registrationCounts[key]<=0;passModal.querySelector('#idUploadField').classList.toggle('required',registrationCounts.senior>0)}
passModal?.querySelectorAll('[data-group]').forEach(row=>{const key=row.dataset.group;row.querySelectorAll('[data-count-action]').forEach(button=>button.addEventListener('click',()=>{const direction=button.dataset.countAction==='plus'?1:-1;const minimum=key==='adult'?1:0;registrationCounts[key]=Math.max(minimum,Math.min(50,registrationCounts[key]+direction));updateGroupRow(key)}));updateGroupRow(key)});
discountIdInput?.addEventListener('change',()=>{const status=passModal.querySelector('#idFileName');const file=discountIdInput.files[0];if(file&&file.size>5*1024*1024){discountIdInput.value='';status.textContent='File is larger than 5 MB';return}status.textContent=file?file.name:'No file selected'});
function renderPaymentSummary(){const summary=passModal.querySelector('#paymentSummary');const rows=Object.keys(registrationCounts).filter(key=>registrationCounts[key]>0).map(key=>`<div class="payment-summary-row"><span>${groupLabel(key)} × ${registrationCounts[key]} ${registrationRates[key]?`@ ₱${registrationRates[key]}`:'(exempted)'}</span><strong>${registrationRates[key]?`₱${(registrationCounts[key]*registrationRates[key]).toFixed(2)}`:'FREE'}</strong></div>`).join('');summary.innerHTML=`${rows}<div class="payment-summary-row total"><span>Total Amount</span><strong>₱${registrationTotal().toFixed(2)}</strong></div>`}
passForm?.addEventListener('submit',event=>{event.preventDefault();const status=passModal.querySelector('[data-pass-status="1"]');status.textContent='';if(registrationCounts.senior>0&&!discountIdInput.files.length){status.textContent='Please upload a valid ID for each senior, PWD, or student.';passModal.querySelector('#idUploadField').focus();return}renderPaymentSummary();showRegistrationStep(2)});
passModal?.querySelector('[data-registration-back]')?.addEventListener('click',()=>showRegistrationStep(1));
function formatPassDate(value){return new Intl.DateTimeFormat('en-PH',{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${value}T00:00:00`))}
function buildPass(){const values=new FormData(passForm);const passId=`ECP-${String(values.get('visitDate')).replaceAll('-','')}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(0,5).toUpperCase()}`;const days=Number.parseInt(values.get('stay'),10)||1;const validUntil=new Date(`${values.get('visitDate')}T00:00:00`);validUntil.setDate(validUntil.getDate()+days-1);return{id:passId,name:String(values.get('fullName')),address:String(values.get('address')),contact:String(values.get('contact')),visitDate:String(values.get('visitDate')),visitDateLabel:formatPassDate(values.get('visitDate')),stay:String(values.get('stay')),validUntil:new Intl.DateTimeFormat('en-PH',{year:'numeric',month:'short',day:'numeric'}).format(validUntil),groups:{...registrationCounts},amount:registrationTotal(),paymentMethod:String(values.get('paymentMethod'))}}
function renderPass(pass){const group=Object.keys(pass.groups).filter(key=>pass.groups[key]>0).map(key=>`${pass.groups[key]} ${groupLabel(key)}`).join(' · ');passModal.querySelector('#passQr').src=`https://api.qrserver.com/v1/create-qr-code/?size=240x240&margin=8&data=${encodeURIComponent(pass.id)}`;passModal.querySelector('#passDetails').innerHTML=[['Pass ID',pass.id],['Name',pass.name],['Group',group],['Date of Visit',pass.visitDateLabel],['Length of Stay',pass.stay],['Valid Until',pass.validUntil],['Amount Due',`₱${pass.amount.toFixed(2)}`],['Payment',pass.paymentMethod]].map(([label,value])=>`<div><dt>${escapeDownload(label)}</dt><dd>${escapeDownload(value)}</dd></div>`).join('')}
passModal?.querySelector('[data-registration-complete]')?.addEventListener('click',()=>{currentPass=buildPass();renderPass(currentPass);showRegistrationStep(3)});
function escapeDownload(value){return String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]))}
function downloadCurrentPass(){if(!currentPass)return;const group=Object.keys(currentPass.groups).filter(key=>currentPass.groups[key]>0).map(key=>`${currentPass.groups[key]} ${groupLabel(key)}`).join(' · ');const qr=`https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=8&data=${encodeURIComponent(currentPass.id)}`;const page=`<!doctype html><meta charset="utf-8"><title>${escapeDownload(currentPass.id)}</title><style>body{font-family:Arial;background:#f5f1e9;color:#173b28;display:grid;place-items:center;min-height:100vh;margin:0}.pass{width:360px;padding:28px;border-radius:24px;background:#fff;box-shadow:0 20px 50px #0002;text-align:center}.qr{padding:22px;border-radius:18px;background:#075d34}.qr img{width:210px;background:#fff;border-radius:10px}.details{text-align:left;line-height:1.8;margin-top:20px}.paid{color:#8a6500;font-weight:bold}</style><main class="pass"><h1>EcoPass</h1><div class="qr"><img src="${qr}" alt="QR code"></div><h2>Visitor Pass</h2><div class="details"><b>Pass ID:</b> ${escapeDownload(currentPass.id)}<br><b>Name:</b> ${escapeDownload(currentPass.name)}<br><b>Group:</b> ${escapeDownload(group)}<br><b>Date:</b> ${escapeDownload(currentPass.visitDateLabel)}<br><b>Length of stay:</b> ${escapeDownload(currentPass.stay)}<br><b>Valid until:</b> ${escapeDownload(currentPass.validUntil)}<br><b>Amount due:</b> ₱${currentPass.amount.toFixed(2)}<br><b>Payment method:</b> ${escapeDownload(currentPass.paymentMethod)}</div><p class="paid">Registration recorded · payment pending</p></main>`;const url=URL.createObjectURL(new Blob([page],{type:'text/html'}));const link=document.createElement('a');link.href=url;link.download=`EcoPass-${currentPass.id}.html`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
passModal?.querySelector('[data-download-pass]')?.addEventListener('click',downloadCurrentPass);
passModal?.querySelector('[data-save-pass]')?.addEventListener('click',()=>{const status=passModal.querySelector('[data-pass-status="3"]');try{localStorage.setItem('ecopassSavedPass',JSON.stringify(currentPass));status.textContent='Pass saved on this device. You can also download a portable copy.';status.classList.add('success')}catch{status.textContent='This browser could not save the pass. Please download it instead.';status.classList.remove('success')}});
passModalClose?.addEventListener('click',closePassModal);
passModal?.addEventListener('click',event=>{if(event.target===passModal)closePassModal()});
passModal?.addEventListener('close',()=>{document.body.classList.remove('modal-open');passModalTrigger?.focus();passModalTrigger=null});
passModal?.addEventListener('cancel',()=>document.body.classList.remove('modal-open'));
if(location.hash==='#pass-modal')openPassModal();
const menu=document.querySelector('.menu-button');menu?.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));document.querySelector('.nav').classList.toggle('open',!expanded)});document.querySelectorAll('.nav a').forEach(link=>link.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');document.querySelector('.nav').classList.remove('open')}));loadContent();
